import BottomBar from './BottomBar'
import SimpleContainer from './SimpleContainer'
import TopBar from './TopBar'
import './globals.css'
import { Inter } from 'next/font/google'
import { ChildrenProps } from '../types/ChildrenProps'
import type { Session } from "next-auth"
import { AppProps } from 'next/app'
import { SessionProvider } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: ChildrenProps) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <SimpleContainer>
                    <TopBar />
                    {children}
                    <BottomBar />
                </SimpleContainer>
            </body>
        </html>
    )
}

