'use client'

import { StyledEngineProvider } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import { ThemeProvider } from '@mui/material/styles'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SimpleContainer from './simple-container'
import './globals.css'
import { PropsWithChildren } from 'react'
import theme from './theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: {
        initialScale: 1,
        width: 'device-width',
    },
}

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <StyledEngineProvider injectFirst>
            <html lang='en'>
                <body className={inter.className}>
                    <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                        <ThemeProvider theme={theme}>
                            <SimpleContainer>{children}</SimpleContainer>
                        </ThemeProvider>
                    </AppRouterCacheProvider>
                </body>
            </html>
        </StyledEngineProvider>
    )
}
