'use client'

import { StyledEngineProvider } from '@mui/material'
import { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ChildrenProps } from '../types/ChildrenProps'
import SimpleContainer from './SimpleContainer'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    viewport: {
        initialScale: 1,
        width: 'device-width',
    },
}

export default function RootLayout({ children }: ChildrenProps) {
    return (
        <StyledEngineProvider injectFirst>
            <html lang='en'>
                <body className={inter.className}>
                    <SimpleContainer>{children}</SimpleContainer>
                </body>
            </html>
        </StyledEngineProvider>
    )
}
